=== Canadian-Geospatial-Platform/geochart/schema-inputs.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GeoChart Inputs Schema",
  "description": "This Schema validator validates the GeoChart Inputs.",
  "type": "object",
  "properties": {
    "chart": {
      "description": "Supported types of Chart.",
      "$ref": "#/$defs/chartTypeEnum",
      "default": "line"
    },
    "title": {
      "description": "Optionally provide the title of the Chart.",
      "type": "string"
    },
    "query": {
      "description": "Optionally provide information on how the data should be queried in the table source. When undefined, the data has to be manually provided via datasources[].items values.",
      "type": "object",
      "properties": {
        "type": {
          "description": "Indicate the kind of query to perform.",
          "$ref": "#/$defs/queryTypeEnum"
        },
        "url": {
          "description": "Indicate the url where to fetch the data to build the Chart with - supported urls are Esri services, OGC API Features services or urls pointing to a .json file built on the GeoJson format.",
          "type": "string"
        },
        "queryOptions": {
          "description": "Query parameters to be used when querying the url.",
          "type": "object",
          "properties": {
            "whereClauses": {
              "description": "Indicate how to generate the where clause to fetch the correct data in the table source. This is an array to support filtering on more than 1 field. The 'and' logic operator is implicit.",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "field": {
                    "description": "Indicate the field name, in the table source, on which to filter.",
                    "type": "string"
                  },
                  "prefix": {
                    "description": "Indicate the prefix to use to build the query (useful to support single-quotes when the attribute to query is a string).",
                    "type": "string"
                  },
                  "valueIs": {
                    "description": "Indicate the value as a literal information (not read from a property name from the datasource).",
                    "type": "string"
                  },
                  "valueFrom": {
                    "description": "Indicate the property name, in the datasource.sourceItem(!), to dynamically read and provide to the query parameters in order to query the table source as indicated by the url.",
                    "type": "string"
                  },
                  "suffix": {
                    "description": "Indicate the suffix to use to build the query (useful to support single-quotes when the attribute to query is a string).",
                    "type": "string"
                  }
                },
                "required": ["field"],
                "oneOf": [
                  { "required": ["valueIs"], "not": { "required": ["valueFrom"] } },
                  { "required": ["valueFrom"], "not": { "required": ["valueIs"] } }
                ]
              }
            },
            "orderByField": {
              "description": "Optionally indicate the property on which to order the results of the data coming from the table source.",
              "type": "string"
            }
          }
        }
      },
      "required": ["type", "url"]
    },
    "geochart": {
      "description": "Groups information on how to build the Chart.",
      "type": "object",
      "properties": {
        "xAxis": {
          "description": "Groups information on the X axis.",
          "type": "object",
          "properties": {
            "property": {
              "description": "Indicate the property name on which to read the information from the table source.",
              "type": "string"
            },
            "type": {
              "description": "Indicate the type of axis.",
              "$ref": "#/$defs/scaleTypeEnum",
              "default": "linear"
            },
            "timeFormat": {
              "description": "Defines the format string(s) used to display or parse time values. Can be a single format string (e.g., 'yyyy-MM-dd HH:mm:ss') or an object with locale-specific format strings keyed by language code (e.g., { \"en\": \"MMM dd, yyyy, HH:mm\", \"fr\": \"d MMM yyyy, HH:mm\" }). Uses standard date formatting tokens (e.g., from date-fns or equivalent). Defaults to 'yyyy-MM-dd HH:mm:ss' if not specified.",
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "object",
                  "properties": {
                    "en": { "type": "string" },
                    "fr": { "type": "string" }
                  },
                  "required": ["en", "fr"],
                  "additionalProperties": false
                }
              ],
              "default": "yyyy-MM-dd HH:mm:ss"
            },
            "timeIANA": {
              "description": "Specifies the IANA time zone identifier (e.g., 'America/Toronto', 'UTC') used for formatting and interpreting time values. Must be a valid time zone from the IANA Time Zone Database.",
              "type": "string",
              "default": "utc"
            },
            "ticksRule": {
              "description": "The rule to apply to provide the X axis ticks. 'auto' automatically calculates the optimal ticks on the axis. 'data' uses the actual data values to set the optimal ticks on the axis.",
              "type": "string",
              "enum": ["auto", "data"],
              "default": "auto"
            },
            "label": {
              "description": "Indicate the label that should be shown for the axis.",
              "type": "string"
            },
            "usePalette": {
              "description": "Optionally indicate a pre-determined (GeoChart specific) color palette should be used.",
              "type": "boolean",
              "default": false
            },
            "paletteBackgrounds": {
              "description": "Optionally indicate an array of rgba color values to use as the palette for background coloring.",
              "type": "array",
              "items": {
                "description": "A rgba() color",
                "type": "string"
              }
            },
            "paletteBorders": {
              "description": "Optionally indicate an array of rgb color values to use as the palette for border coloring.",
              "type": "array",
              "items": {
                "description": "A rgb() color",
                "type": "string"
              }
            }
          },
          "required": ["property"]
        },
        "yAxis": {
          "description": "Groups information on the Y axis.",
          "type": "object",
          "properties": {
            "property": {
              "description": "Indicate the property name on which to read the information from the table source.",
              "type": "string"
            },
            "type": {
              "description": "Indicate the type of axis.",
              "$ref": "#/$defs/scaleTypeEnum",
              "default": "linear"
            },
            "label": {
              "description": "Indicate the label that should be shown for the axis.",
              "type": "string"
            },
            "usePalette": {
              "description": "Optionally indicate a pre-determined (GeoChart specific) color palette should be used.",
              "type": "boolean",
              "default": false
            },
            "paletteBackgrounds": {
              "description": "Optionally indicate an array of rgba color values to use as the palette for background coloring.",
              "type": "array",
              "items": {
                "description": "A rgba() color",
                "type": "string"
              }
            },
            "paletteBorders": {
              "description": "Optionally indicate an array of rgb color values to use as the palette for border coloring.",
              "type": "array",
              "items": {
                "description": "A rgb() color",
                "type": "string"
              }
            },
            "tooltipSuffix": {
              "description": "Optionally indicate the suffix to use on for the values when displayed in the Chart tooltip.",
              "type": "string"
            }
          },
          "required": ["property"]
        },
        "borderWidth": {
          "description": "Optionally indicate the thickness of the borders (or lines in the line Chart).",
          "type": "number"
        },
        "useSteps": {
          "description": "Optionally indicate if the line Chart should use steps.",
          "oneOf": [
            { "$ref": "#/$defs/stepTypeEnum" },
            { "const": false }
          ],
          "default": false
        },
        "tension": {
          "description": "Optionally indicate if the Chart should use tension when drawing the line between the values (only possible with a line type Chart).",
          "type": "number"
        }
      },
      "required": ["xAxis", "yAxis"]
    },
    "category": {
      "description": "Optionally indicate how the data from the table source should be categorized (this creates the datasets aka the legend).",
      "type": "object",
      "properties": {
        "property": {
          "description": "Indicate the property name to use to categorize records.",
          "type": "string"
        },
        "usePalette": {
          "description": "Optionally indicate a pre-determined (GeoChart specific) color palette should be used.",
          "type": "boolean",
          "default": false
        },
        "paletteBackgrounds": {
          "description": "Optionally indicate an array of rgba color values to use as the palette for background coloring.",
          "type": "array",
          "items": {
            "description": "A rgba() color",
            "type": "string"
          }
        },
        "paletteBorders": {
          "description": "Optionally indicate the array of rgb color values to use as the palette for border coloring.",
          "type": "array",
          "items": {
            "description": "A rgb() color",
            "type": "string"
          }
        }
      },
      "required": ["property"]
    },
    "datasources": {
      "description": "Groups information on the datasources to build the datasource drop down and the Chart.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "display": {
            "description": "Indicate the string to be displayed in the drop down.",
            "type": "string"
          },
          "sourceItem": {
            "description": "Optionally indicate the source item(!) used when fetching the data using the 'query.url'. The source items represent the features loaded in the drop down. This property has an object with a property that should equal the property in 'query.queryOptions.whereClauses.valueFrom'.",
            "type": "object"
          },
          "value": {
            "description": "Optionally indicate the inner value used for the 'sourceItem' - when 'display' alone isn't sufficient to distinguish the values.",
            "anyOf": [
              { "type": "string" },
              { "type": "number" }
            ]
          },
          "items": {
            "description": "Optionally indicate the actual items used to build the Chart. When a query.url is specified, the items will be fetched automatically. When items are specified/populated, the data isn't fetched via the 'query.url'.",
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": ["display"]
      }
    },
    "ui": {
      "description": "Optionally indicate what UI elements to show alongside the Chart.",
      "type": "object",
      "properties": {
        "xSlider": {
          "description": "Groups information on the X axis slider.",
          "type": "object",
          "properties": {
            "display": {
              "description": "Indicate if the slider on the X axis should be displayed.",
              "type": "boolean"
            },
            "step": {
              "description": "Optionally indicate the steps the slider should jump when sliding.",
              "type": "number"
            },
            "min": {
              "description": "Optionally indicate the minimum value for the slider.",
              "type": "number"
            },
            "max": {
              "description": "Optionally indicate the maximum value for the slider.",
              "type": "number"
            }
          },
          "required": ["display"]
        },
        "ySlider": {
          "description": "Groups information on the Y axis slider.",
          "type": "object",
          "properties": {
            "display": {
              "description": "Optionally indicate if the slider on the Y axis should be displayed",
              "type": "boolean"
            },
            "step": {
              "description": "Optionally indicate the steps the slider should jump when sliding.",
              "type": "number"
            },
            "min": {
              "description": "Optionally indicate the minimum value for the slider.",
              "type": "number"
            },
            "max": {
              "description": "Optionally indicate the maximum value for the slider.",
              "type": "number"
            }
          },
          "required": ["display"]
        },
        "stepsSwitcher": {
          "description": "Optionally indicate if a drop down should be shown allowing to switch the steps on-the-fly.",
          "oneOf": [
            {
              "type": "array",
              "items": {
                "oneOf": [
                  { "$ref": "#/$defs/stepTypeEnum" },
                  { "const": false }
                ]
              },
              "minItems": 1,
              "uniqueItems": true
            },
            { "type": "boolean" }
          ],
          "default": false
        },
        "scalesSwitcher": {
          "description": "Optionally indicate if a drop down should be shown allowing to switch the scales on-the-fly.",
          "oneOf": [
            {
              "type": "array",
              "items": { "$ref": "#/$defs/scaleTypeEnum" },
              "minItems": 1,
              "uniqueItems": true
            },
            { "type": "boolean" }
          ],
          "default": false
        },
        "resetStates": {
          "description": "Optionally indicate if the button to reset the states should be displayed.",
          "type": "boolean",
          "default": false
        },
        "description": {
          "description": "Optionally indicate descriptive text to show at the bottom of the Chart.",
          "type": "string"
        },
        "download": {
          "description": "Optionally indicate if a download button should be displayed.",
          "type": "boolean",
          "default": false
        }
      }
    },
    "chartjsOptions": {
      "description": "Optionally indicate further ChartJS specific options to open the door to further customization when natively supported by ChartJS: https://www.chartjs.org/docs/latest/general/options.html",
      "type": "object"
    }
  },
  "required": ["chart", "geochart", "datasources"],
  "$defs": {
    "chartTypeEnum": {
      "type": "string",
      "enum": ["line", "bar", "pie", "doughnut"]
    },
    "queryTypeEnum": {
      "type": "string",
      "enum": ["esriRegular", "ogcAPIFeatures", "json"]
    },
    "scaleTypeEnum": {
      "type": "string",
      "enum": ["linear", "logarithmic", "category", "time", "timeseries"]
    },
    "stepTypeEnum": {
      "type": "string",
      "enum": ["before", "after", "middle"]
    }
  }
}

=== Canadian-Geospatial-Platform/geochart/public/configs/config-bar-1-single.json
{
  "chart": "bar",
  "title": "Bar Chart with OGC Features",
  "query": {
    "type": "ogcAPIFeatures",
    "url": "https://demo.pygeoapi.io/master/collections/lakes",
    "queryOptions": {
      "whereClauses": [
        {
          "field": "name",
          "prefix": "",
          "valueFrom": "name",
          "suffix": ""
        }
      ]
    }
  },
  "geochart": {
    "xAxis": {
      "property": "name",
      "label": "Name"
    },
    "yAxis": {
      "property": "id",
      "label": "ID"
    }
  },
  "ui": {
    "resetStates": true,
    "download": true
  },
  "datasources": [
    {
      "display": "Lake Ontario",
      "sourceItem": {
        "name": "L. Ontario"
      }
    },
    {
      "display": "Lake Erie",
      "sourceItem": {
        "name": "L. Erie"
      }
    }
  ]
}

=== Canadian-Geospatial-Platform/geochart/public/configs/config-line-2.json
{
  "chart": "line",
  "title": "Line Chart with time on x and sliders and steps|tension",
  "query": {
    "type": "esriRegular",
    "url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/airborne_radioactivity_en/MapServer/3",
    "queryOptions": {
      "whereClauses": [
        {
          "field": "Location_Emplacement",
          "prefix": "'",
          "valueFrom": "Location_Emplacement",
          "suffix": "'"
        }
      ],
      "orderByField": "CollectionStart_DebutPrelevement"
    }
  },
  "geochart": {
    "borderWidth": 2,
    "useSteps": "after",
    "tension": 0.3,
    "xAxis": {
      "type": "time",
      "timeFormat": "MMM d, yyyy, HH:mm",
      "timeIANA": "Europe/Paris",
      "property": "CollectionStart_DebutPrelevement",
      "label": "Collected date",
      "usePalette": false
    },
    "yAxis": {
      "type": "logarithmic",
      "property": "Activity_Activite_mBqm3",
      "label": "Activity (mBqm3)"
    }
  },
  "category": {
    "property": "Radionuclide_Radionucleide",
    "usePalette": false
  },
  "ui": {
    "xSlider": {
      "display": true
    },
    "ySlider": {
      "display": true,
      "step": 0.1
    },
    "scalesSwitcher": ["linear", "logarithmic"],
    "stepsSwitcher": ["middle", "after"]
  },
  "datasources": [
    {
      "display": "Vancouver",
      "sourceItem": {
        "Location_Emplacement": "Vancouver"
      }
    },
    {
      "display": "Regina",
      "sourceItem": {
        "Location_Emplacement": "Regina"
      }
    },
    {
      "display": "Ottawa",
      "sourceItem": {
        "Location_Emplacement": "Ottawa"
      }
    },
    {
      "display": "Montreal",
      "sourceItem": {
        "Location_Emplacement": "Montreal"
      }
    },
    {
      "display": "Quebec",
      "sourceItem": {
        "Location_Emplacement": "Quebec"
      }
    }
  ]
}

=== Canadian-Geospatial-Platform/geochart/public/configs/config-line-2-slim.json
{
  "chart": "line",
  "title": "Line Chart slim config",
  "query": {
    "type": "esriRegular",
    "url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/airborne_radioactivity_en/MapServer/3",
    "queryOptions": {
      "whereClauses": [
        {
          "field": "Location_Emplacement",
          "prefix": "'",
          "valueFrom": "Location_Emplacement",
          "suffix": "'"
        }
      ],
      "orderByField": "CollectionStart_DebutPrelevement"
    }
  },
  "geochart": {
    "xAxis": {
      "type": "time",
      "timeFormat": "MMM d, yyyy, HH:mm",
      "property": "CollectionStart_DebutPrelevement"
    },
    "yAxis": {
      "property": "Activity_Activite_mBqm3"
    }
  },
  "category": {
    "property": "Radionuclide_Radionucleide",
    "usePalette": false
  },
  "datasources": [
    {
      "display": "Vancouver",
      "sourceItem": {
        "Location_Emplacement": "Vancouver"
      }
    },
    {
      "display": "Regina",
      "sourceItem": {
        "Location_Emplacement": "Regina"
      }
    }
  ]
}

=== Canadian-Geospatial-Platform/geochart/configs/config-line-5.json
{
  "chart": "line",
  "title": "Line Chart with time on x and sliders",
  "query": {
    "type": "esriRegular",
    "url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/alphabeta_water_fr/MapServer/3",
    "queryOptions": {
      "whereClauses": [
        {
          "field": "Emplacement_FR",
          "prefix": "'",
          "valueFrom": "Emplacement_FR",
          "suffix": "'"
        }
      ],
      "format": "json",
      "orderByField": "StartDate_DateDebut"
    }
  },
  "geochart": {
    "xAxis": {
      "type": "time",
      "property": "StartDate_DateDebut",
      "label": "Collected date"
    },
    "yAxis": {
      "property": "Activity_Activite_BqL",
      "label": "Some value"
    },
    "borderWidth": 1
  },
  "ui": {
    "description": "This is EGS_Flood_Product_Active_AGOL",
    "download": true
  },
  "datasources": [
    {
      "display": "Britannia Fr",
      "sourceItem": {
        "Emplacement_FR": "Usine de purification de l'eau Britannia"
      }
    }
  ]
}

=== Canadian-Geospatial-Platform/geochart/public/configs/config-line-ogc-1.json
{
  "chart": "line",
  "title": "Line Chart with OGC Features",
  "query": {
    "type": "ogcAPIFeatures",
    "url": "https://pygeoapi-stage.cdtk.geogc.ca/collections/ft::seismic_reflection:seismic_reflection_imagery",
    "queryOptions": {
      "whereClauses": [
        {
          "field": "YEAR",
          "valueFrom": "YEAR"
        }
      ]
    }
  },
  "geochart": {
    "xAxis": {
      "type": "time",
      "timeFormat": "MMM d, yyyy, HH:mm",
      "property": "DATE_START"
    },
    "yAxis": {
      "property": "YEAR"
    }
  },
  "ui": {
    "resetStates": true,
    "download": true
  },
  "datasources": [
    {
      "display": "1996",
      "sourceItem": {
        "YEAR": 1996
      }
    },
    {
      "display": "1997",
      "sourceItem": {
        "YEAR": 1997
      }
    },
    {
      "display": "1998",
      "sourceItem": {
        "YEAR": 1998
      }
    },
    {
      "display": "1999",
      "sourceItem": {
        "YEAR": 1999
      }
    },
    {
      "display": "2000",
      "sourceItem": {
        "YEAR": 2000
      }
    }
  ]
}

=== Canadian-Geospatial-Platform/geochart/public/configs/config-line-1.json
{
  "chart": "line",
  "title": "Line Chart with time on x and sliders",
  "query": {
    "type": "esriRegular",
    "url": "https://maps-cartes.services.geo.ca/server_serveur/rest/services/HC/airborne_radioactivity_en/MapServer/3",
    "queryOptions": {
      "whereClauses": [
        {
          "field": "Location_Emplacement",
          "prefix": "'",
          "valueFrom": "Location_Emplacement",
          "suffix": "'"
        }
      ],
      "orderByField": "CollectionStart_DebutPrelevement"
    }
  },
  "geochart": {
    "borderWidth": 2,
    "xAxis": {
      "type": "time",
      "timeFormat": {
        "en": "MMM d, yyyy, HH:mm",
        "fr": "d MMM yyyy, HH:mm"
      },
      "timeIANA": "America/Toronto",
      "ticksRule": "auto",
      "property": "CollectionStart_DebutPrelevement",
      "label": "Collected date"
    },
    "yAxis": {
      "type": "linear",
      "property": "Activity_Activite_mBqm3",
      "label": "Activity mBqm3",
      "tooltipSuffix": "mBqm3"
    }
  },
  "category": {
    "property": "Radionuclide_Radionucleide"
  },
  "ui": {
    "xSlider": {
      "display": true
    },
    "ySlider": {
      "display": true,
      "step": 0.1
    },
    "stepsSwitcher": true,
    "scalesSwitcher": true,
    "resetStates": true,
    "description": "This is a description text",
    "download": true
  },
  "datasources": [
    {
      "display": "Saskatoon",
      "sourceItem": {
        "Location_Emplacement": "Saskatoon"
      }
    },
    {
      "display": "Vancouver",
      "sourceItem": {
        "Location_Emplacement": "Vancouver"
      }
    },
    {
      "display": "Regina",
      "sourceItem": {
        "Location_Emplacement": "Regina"
      }
    },
    {
      "display": "Ottawa",
      "sourceItem": {
        "Location_Emplacement": "Ottawa"
      }
    },
    {
      "display": "Montreal",
      "sourceItem": {
        "Location_Emplacement": "Montreal"
      }
    },
    {
      "display": "Quebec",
      "sourceItem": {
        "Location_Emplacement": "Quebec"
      }
    }
  ]
}

=== Canadian-Geospatial-Platform/geochart/configs/config-bar-1.json
{
  "chart": "bar",
  "title": "Bar Chart with OGC Features",
  "query": {
    "type": "ogcAPIFeatures",
    "url": "https://demo.pygeoapi.io/master/collections/lakes"
  },
  "geochart": {
    "xAxis": {
      "property": "name",
      "label": "Name"
    },
    "yAxis": {
      "property": "id",
      "label": "ID"
    }
  },
  "ui": {
    "resetStates": true,
    "download": true
  },
  "datasources": [
    {
      "display": "Lakes"
    }
  ]
}

=== Canadian-Geospatial-Platform/geochart/configs/config-doughnut-1.json
{
  "chart": "doughnut",
  "title": "Doughnut Chart",
  "geochart": {
    "xAxis": {
      "property": "Location_Emplacement",
      "usePalette": false
    },
    "yAxis": {
      "property": "Activity_Activite_mBqm3"
    }
  },
  "category": {
    "property": "Radionuclide_Radionucleide",
    "usePalette": false
  },
  "ui": {
    "resetStates": true,
    "download": true
  },
  "datasources": [
    {
      "value": "1",
      "display": "Feature 1",
      "items": [
        {
          "Location_Emplacement": "Victoria",
          "CollectionStart_DebutPrelevement": 1678320000000,
          "Radionuclide_Radionucleide": "7Be",
          "Activity_Activite_mBqm3": 2.7395,
          "OBJECTID": 56874
        },
        {
          "Location_Emplacement": "Vancouver",
          "CollectionStart_DebutPrelevement": 1669248000000,
          "Radionuclide_Radionucleide": "7Be",
          "Activity_Activite_mBqm3": 0.83,
          "OBJECTID": 56875
        },
        {
          "Location_Emplacement": "Vancouver",
          "CollectionStart_DebutPrelevement": 1669248000000,
          "Radionuclide_Radionucleide": "7Be",
          "Activity_Activite_mBqm3": 0.83,
          "OBJECTID": 56871
        },
        {
          "Location_Emplacement": "Yellowknife",
          "CollectionStart_DebutPrelevement": 1679443200000,
          "Radionuclide_Radionucleide": "210Pb",
          "Activity_Activite_mBqm3": 1.0166,
          "OBJECTID": 56876
        },
        {
          "Location_Emplacement": "Vancouver",
          "CollectionStart_DebutPrelevement": 1678406400000,
          "Radionuclide_Radionucleide": "210Pb",
          "Activity_Activite_mBqm3": 0.939,
          "OBJECTID": 56877
        },
        {
          "Location_Emplacement": "Montreal",
          "CollectionStart_DebutPrelevement": 1679011200000,
          "Radionuclide_Radionucleide": "210Pb",
          "Activity_Activite_mBqm3": 1.1814,
          "OBJECTID": 56878
        },
        {
          "Location_Emplacement": "Toronto",
          "CollectionStart_DebutPrelevement": 1677974400000,
          "Radionuclide_Radionucleide": "210Pb",
          "Activity_Activite_mBqm3": 0.6715,
          "OBJECTID": 56879
        },
        {
          "Location_Emplacement": "Montreal",
          "CollectionStart_DebutPrelevement": 1668643200000,
          "Radionuclide_Radionucleide": "7Be",
          "Activity_Activite_mBqm3": 3.2589,
          "OBJECTID": 56880
        }
      ]
    }
  ]
}
